import { Inter } from 'next/font/google'
import { useAuth, SignIn } from '@clerk/nextjs'
import { useRouter } from 'next/router'
import Head from 'next/head'
//import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { isLoaded, userId, sessionId, getToken } = useAuth();
  const router = useRouter()

  // user is logged in, automatically redirect to /todos
  if(userId){
    router.push('/todos')
  } 
  // user is not logged in, render root page with title and clerk signIn
  else {
    return (
      <>
        <Head>
          <title> React App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className="splash-container">
          <div className="splash-header-container">
            <span className="splash-title1">Ola Oladeji</span>
            <span className="splash-title2">Task List!</span>

          </div>
       
          <SignIn className="splash-signIn"/>
        </div>
      </>
    )
  }
  
}