import ToDoList from '../components/ToDoItem'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useAuth } from '@clerk/nextjs'
import NavBar from '../components/NavBar'
import { useEffect } from "react"

export default function Todos() {
  const { isLoaded, userId, sessionId, getToken } = useAuth();
  const router = useRouter()
  
  useEffect(() => {
    if(!userId){
      router.push('/')
    }
  });
  
    return (
      <>
        <Head>
          <title>React App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <NavBar/>
        <ToDoList done={false}/>
      </>
    )
  }